# learning recipe
lr: 0.001
noise_dim: 100
iter: 100
batch_size: 32
l_percep: 0.3
l_dom: 0.4

# others
device: 'cuda'
save_path: 'inverted_img'
target_img: 'source.jpg'
G_weight: 'generator.pt'
enc_weight: 'encoder.pt'
target_shape: 64